using TSISP003_Net.SignControllerDataStore.Entities;
using static TSISP003_Net.Utils.Enums;

namespace TSISP003.SignControllerService;

public interface ISignControllerService : IHostedService
{
    Task<SignStatusReply> GetStatus();
    Task<SignController> GetControllerConfigurationAsync();
    Task StartSession();
    Task Password(string passwordSeed);
    Task HeartbeatPoll();
    Task EndSession();
    Task SystemReset(byte groupId, byte resetLevel);
    Task UpdateTime();
    Task<SignStatusReply> SignSetTextFrame(SignSetTextFrame request);
    Task SignSetGraphicsFrame();
    Task SignSetHighResolutionGraphicsFrame();
    Task SignConfigurationRequest();
    Task SignDisplayAtomicFrames();
    Task<SignStatusReply> SignSetMessage(SignSetMessage request);
    Task SignSetPlan();
    Task SignDisplayFrame();
    Task<AckReply> SignDisplayMessage(SignDisplayMessage request);
    Task EnablePlan();
    Task DisablePlan();
    Task RequestEnabledPlans();
    Task SignSetDimmingLevel();
    Task PowerOnOff();
    Task DisableEnableDevice();
    Task<ISignResponse> SignRequestStoredFrameMessagePlan(RequestType requestType, byte requestID);
    Task SignExtendedStatusRequest();
    Task<List<FaultLogEntry>> RetrieveFaultLog();
    Task ResetFaultLog();
    Task HARSetVoiceDataIncomplete();
    Task HARSetVoiceDataComplete();
    Task HARSetStrategy();
    Task HARActivateStrategy();
    Task HARSetPlan();
    Task HARRequestStoredVoiceStrategyPlan();
    Task RequestEnvironmentalWeatherValues();
    Task EnvironmentalWeatherValues();
    Task EnvironmentalWeatherThresholdDefinition();
    Task RequestThresholdDefinition();
    Task RequestEnvironmentalWeatherEventLog();
    Task ResetEnvironmentalWeatherEventLog();
    Task ProcessPasswordSeed(string applicationData);
    Task ProcessAcknowledge(string applicationData);
    Task ProcessSignStatusReply(string applicationData);
    Task ProcessHARStatusReply(string applicationData);
    Task ProcessEnvironmentalWeatherStatusReply(string applicationData);
    Task ProcessSignConfigurationReply(string applicationData);
    Task ProcessReportEnabledPlans(string applicationData);
    Task ProcessSignExtendedStatusReply(string applicationData);
    Task ProcessFaultLogReply(string applicationData);
    Task ProcessHARVoiceDataAck(string applicationData);
    Task ProcessHARVoiceDataNak(string applicationData);
    Task ProcessEnvironmentalWeatherValuesReply(string applicationData);
    Task ProcessEnvironmentalWeatherThresholdDefinitionReply(string applicationData);
    Task ProcessEnvironmentalWeatherEventLogReply(string applicationData);
    Task ProcessSignSetTextFrame(string applicationData);
    Task ProcessSignSetGraphicsFrame(string applicationData);
    Task ProcessSignSetHighResolutionGraphicsFrame(string applicationData);
    Task ProcessSignSetMessage(string applicationData);
    Task ProcessSignSetPlan(string applicationData);
    Task ProcessRejectMessage(string applicationData);
    Task ProcessAckMessage(string applicationData);
}