namespace TSISP003.Domain.Constants;

public static class ErrorCodes
{
    public static readonly Dictionary<byte, string> ControllerDeviceErrorCodes = new()
    {
        { 0x00, "No Error" },
        { 0x01, "Lamp failure - one or more lamps/LEDs are defective" },
        { 0x02, "Less than 50% of the lamps/LEDs are functional" },
        { 0x03, "Power supply error" },
        { 0x04, "Conflicting frame" },
        { 0x05, "Frame sequence error" },
        { 0x06, "Colour error" },
        { 0x07, "Temperature alarm" },
        { 0x08, "Communication error" },
        { 0x09, "Cut off" },
        { 0x0A, "Critical temperature" },
        { 0x0B, "Door alarm" },
        { 0x0C, "Brightness sensor error" },
        { 0x0D, "Display overridden locally" },
        { 0x0E, "Express link error" },
        { 0x0F, "Fan alarm" },
        { 0x10, "Battery Alarm" },
        { 0x11, "Main power failure" },
        { 0x12, "Current overload" },
        { 0x13, "Emergency vehicle preemption" },
        { 0x14, "Transit signal priority" },
        { 0x15, "Pedestrian detection fault" },
        { 0x16, "Sensor fault" },
        { 0x17, "Watchdog error" },
        { 0x18, "Memory error" },
        { 0x19, "Display test active" },
        { 0x1A, "Daylight sensor error" },
        { 0x1B, "Voltage error" },
        { 0x1C, "Fuse error" },
        { 0x1D, "Module error" },
        { 0x1E, "Relay error" },
        { 0x1F, "Switch error" },
        { 0x20, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x21, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x22, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x23, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x24, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x25, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x26, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x27, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x28, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x29, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x2A, "Other device specific error (refer to manufacturer's documentation)" },
        { 0x99, "Unknown/unspecified error" }
    };

    public static readonly Dictionary<byte, string> ApplicationErrorCodes = new()
    {
        { 0x00, "No Error" },
        { 0x01, "Request rejected" },
        { 0x02, "Message Integrity error (wrong CRC)" },
        { 0x03, "Syntax error" },
        { 0x04, "Out of range" },
        { 0x05, "No session" },
        { 0x06, "Insufficient access" },
        { 0x07, "Not supported" },
        { 0x08, "Device busy" },
        { 0x09, "Memory full" },
        { 0x0A, "Invalid frame reference" },
        { 0x0B, "Invalid message reference" },
        { 0x0C, "Invalid plan reference" },
        { 0x0D, "Invalid font reference" },
        { 0x0E, "Invalid colour" },
        { 0x0F, "Invalid group" },
        { 0x10, "Invalid sign" },
        { 0x11, "Invalid frame" },
        { 0x12, "Invalid message" },
        { 0x13, "Invalid plan" },
        { 0x14, "Frame in use" },
        { 0x15, "Message in use" },
        { 0x16, "Plan in use" },
        { 0x17, "Invalid data" },
        { 0x18, "Conspicuity device error" },
        { 0x19, "Internal buffer overflow" },
        { 0x1A, "Sequence error" },
        { 0x1B, "Duplicate plan entry" },
        { 0x1C, "Invalid HAR voice ID" },
        { 0x1D, "Invalid HAR strategy ID" },
        { 0x1E, "Invalid HAR plan ID" },
        { 0x1F, "HAR voice data sequence error" },
        { 0x20, "HAR voice data checksum error" },
        { 0x21, "HAR voice data too large" },
        { 0x22, "HAR voice data format error" },
        { 0x23, "HAR strategy in use" },
        { 0x24, "HAR plan in use" },
        { 0x25, "Other (refer to manufacturer)" }
    };
}
